services:


  sr-api-gateway:
    container_name: sr-api-gateway
    build: ../../ApiGateway
    environment:
      - SERVER_PORT=${ENV_API_GATEWAY_PORT}
      # microservices
      - USER_SERVICE=${ENV_EUREKA_USERS_SERVICE_URL}
      - TASK_SERVICE=${ENV_EUREKA_TASKS_SERVICE_URL}
      - PROJECT_SERVICE=${ENV_EUREKA_PROJECTS_SERVICE_URL}
      - ANALYTICS_SERVICE=${ENV_EUREKA_ANALYTICS_SERVICE_URL}
    ports:
      - ${ENV_API_GATEWAY_PORT}:${ENV_API_GATEWAY_PORT}
    networks:
      - microservices-network
    depends_on:
      - sr-user-service
      - sr-task-service
      - sr-project-service
      - sr-analytics-service
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  sr-user-service:
    container_name: sr-users-service
    build: ../../UserServiceReactive
    ports:
      - "8001:8001"
    environment:
      - SERVER_PORT=${ENV_USERS_SERVICE_PORT}
      # PostgreSQL
      - APP_POSTGRESQL_HOST=${ENV_APP_POSTGRESQL_HOST}
      - APP_POSTGRESQL_PORT=${ENV_APP_POSTGRESQL_PORT}
      - APP_POSTGRESQL_NAME=${ENV_USERS_SERVICE_DATABASE}
      - APP_POSTGRESQL_USER=${ENV_APP_POSTGRESQL_USER}
      - APP_POSTGRESQL_PASSWORD=${ENV_APP_POSTGRESQL_PASSWORD}
#    depends_on:
#      - postgres
    networks:
      - microservices-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  sr-task-service:
    container_name: sr-task-service
    build: ../../TaskServiceReactive
    ports:
      - "8002:8002"
    environment:
      - SERVER_PORT=${ENV_TASKS_SERVICE_PORT}
      # PostgreSQL
      - APP_POSTGRESQL_HOST=${ENV_APP_POSTGRESQL_HOST}
      - APP_POSTGRESQL_PORT=${ENV_APP_POSTGRESQL_PORT}
      - APP_POSTGRESQL_NAME=${ENV_TASKS_SERVICE_DATABASE}
      - APP_POSTGRESQL_USER=${ENV_APP_POSTGRESQL_USER}
      - APP_POSTGRESQL_PASSWORD=${ENV_APP_POSTGRESQL_PASSWORD}
      #Kafka
      - KAFKA_URL=${ENV_KAFKA_URL}
#    depends_on:
#      - postgres
    networks:
      - microservices-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  sr-project-service:
    container_name: sr-projects-service
    build: ../../ProjectServiceReactive
    ports:
      - "8003:8003"
    environment:
      - SERVER_PORT=${ENV_PROJECTS_SERVICE_PORT}
      # PostgreSQL
      - APP_POSTGRESQL_HOST=${ENV_APP_POSTGRESQL_HOST}
      - APP_POSTGRESQL_PORT=${ENV_APP_POSTGRESQL_PORT}
      - APP_POSTGRESQL_NAME=${ENV_PROJECTS_SERVICE_DATABASE}
      - APP_POSTGRESQL_USER=${ENV_APP_POSTGRESQL_USER}
      - APP_POSTGRESQL_PASSWORD=${ENV_APP_POSTGRESQL_PASSWORD}
#    depends_on:
#      - postgres
    networks:
      - microservices-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Analytics Service
  sr-analytics-service:
    container_name: sr-analytics-service
    build: ../../AnalyticsServiceReactive
    ports:
      - "8004:8004"
    environment:
      - SERVER_PORT=${ENV_ANALYTICS_SERVICE_PORT}
      # PostgreSQL
      - APP_POSTGRESQL_HOST=${ENV_APP_POSTGRESQL_HOST}
      - APP_POSTGRESQL_PORT=${ENV_APP_POSTGRESQL_PORT}
      - APP_POSTGRESQL_NAME=${ENV_USERS_SERVICE_DATABASE}
      - APP_POSTGRESQL_USER=${ENV_APP_POSTGRESQL_USER}
      - APP_POSTGRESQL_PASSWORD=${ENV_APP_POSTGRESQL_PASSWORD}
      # Kafka
      - KAFKA_URL=${ENV_KAFKA_URL}
#    depends_on:
#      - postgres
#      - kafka
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
